Protocol client abstraction
tum-esi/WoT.Net pull request #9
Opened 2024-08-13 13:00 UTC by marzi333

Protocol Client Abstraction Layer:
Separated the handling of requests and responses from within the interaction affordance operations in the ConsumedThing to be handled instead by ProtocolClients. 
Now, each Consumer can have multiple protocol clients (eg. HTTP, Coap..etc) so long as the client implements the IProtocolClient interface. After consuming the ThingDescription, the ConsumedThing fetches the protocol client when reading/writing resources in order to send GET/PUT/POST requests.

2024-08-13 13:24 UTC, egekorkan requested changes
just saw some quick improvements

2024-08-13 13:24 UTC, egekorkan commented on README.md
> +<!-- first commit -->
This comment should be removed and how new bindings can be implemented should be explained

2024-08-13 13:24 UTC, egekorkan commented on SimpleHTTPConsumerTester/Program.cs
> +﻿// See https://aka.ms/new-console-template for more informatio5n
```suggestion
﻿// See https://aka.ms/new-console-template for more information
```

2025-01-16 20:07 UTC, egekorkan commented
@FadySalama @marzi333 any updates on this PR? Why it is not merged yet?

2025-01-16 20:08 UTC, FadySalama commented
Did not merge because I didn't test this yet. Is there any urgent need for it?

2025-01-17 07:59 UTC, merged

2025-01-17 08:47 UTC, egekorkan commented
> Did not merge because I didn't test this yet. Is there any urgent need for it?

Mostly to not have old stuff before showing it to others :)